# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateField()),
                ('description', models.TextField()),
                ('is_major', models.BooleanField(default=False)),
            ],
        ),
    ]
