# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 04:47
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.IntegerField(verbose_name=builtins.id),
        ),
    ]
